physics: false
debug: true

generator:
  paused: false
  iteration_delay: 1500 #ms
  items_to_generate: 100000000
  ground_name: "ground_geom"
  data:
    save: true
    out_dir: "/home/arvc/datasets/test"
    binary: true

sensor:
  name: "os1"
  topic: "/os1/pointCloud" #debe coincidir con el topic del sensor en el archivo sdf del sensor
  model_path: "/home/arvc/workSpaces/arvc_ws/src/arvc_gazebo_models/models/os1_gpu" #cpu not working
  collision_offset: 0.05 #m

paralellepipeds:
  item_count: 40
  model_path: "/home/arvc/workSpaces/arvc_ws/src/arvc_gazebo_models/models/BASE_MODELS/simple_block_v2"
  move: true
  change_iteration: 100 #randomize the models each X iteration. If 0, the models will not change
  length: [0.4, 3.0]
  width: [0.05, 0.3]
  height: [0.05, 0.3]
  position:
    min: [-7, -7, -1]
    max: [7, 7, 7]

environment:
  item_count: 30
  model_path: "/home/arvc/workSpaces/arvc_ws/src/arvc_gazebo_models/models/pine_1"
  move: true
  change_iteration: 100 #randomize the models each X iteration. If 0, the models will not change
  scale: [0.5, 3]
  length: [0.5, 3]
  width: [0.5, 3]
  height: [0.5, 3]
  position:
    min: [-50, -50, 0.1]
    max: [50, 50, 0.1]