gazebo:
  physics:

debug:
  enable: false

generator:
  paused: false
  iteration_delay: 1000 #ms
  items_to_generate: 10000
  data:
    out_dir: ""
    save: true
    binary: true

sensor:
  name: "os1"
  topic: "os1/pointcloud"
  model_path: ""
  collision_offset: 0.05 #m

paralepipeds:
  item_count: 50
  lenght: [0.1, 0.5]
  width: [0.05, 0.3]
  height: [0.05, 0.3]

